### ISSUE TITLE
angular2 ng for not working

### ISSUE THREAD

**Issue by RobertRajcool** [drewgreenwell/MetroJS#1]
![testbug](https://cloud.githubusercontent.com/assets/17331229/23023458/b520a72a-f47b-11e6-8cc3-a7beaa11a5c9.png)

**Comment by drewgreenwell** [comment]
Hi this is likely an issue with the timing for your call to liveTile(). You'll want to make sure and wait until after the tiles have been initialized by angular before calling .liveTile
