### ISSUE TITLE
issue faced while importing metro.js.

### ISSUE THREAD

**Issue by adithyavalsaraj** [drewgreenwell/MetroJS#2]
**i was facing this error**

![issue metro js](https://user-images.githubusercontent.com/17118201/27178931-ff1ebf76-51e9-11e7-9222-49de11a60dbb.jpg)

**i found solution by simply editing MetroJs.scss file by adding "/" in path as in following image**

![image](https://user-images.githubusercontent.com/17118201/27179211-36ee5456-51eb-11e7-9942-86630394b564.png)

please help with better solution

**Comment by drewgreenwell** [comment]
Hi, It looks like you are using the Full version of Metro JS which includes the .applicationBar. You can choose a version with only .liveTile and themes on my site or you can grab the images from here or from the zip file.

Image Files
https://github.com/drewgreenwell/MetroJS/tree/master/src/images
Download option. Uncheck Application Bar
http://www.drewgreenwell.com/projects/metrojs#download
